force corepack enable and allow node 23+

diff --git a/ui/build b/ui/build
--- a/ui/build
+++ b/ui/build
@@ -1,14 +1,17 @@
-#!/usr/bin/env bash
+#!/usr/bin/env bash -e
 
-set -e
+MIN_NODE="v22.6.0"
+
+CUR_NODE=$(node -v 2>/dev/null || echo "v0.0.0")
+LOWEST="$(printf "%s\n%s" "$MIN_NODE" "$CUR_NODE" | sort -V | head -n 1)"
+if [ "$LOWEST" != "$MIN_NODE" ]; then
+  echo "Nodejs $MIN_NODE or later is required."
+  exit 1
+fi
 
 cd "$(dirname "${BASH_SOURCE:-$0}")/.build"
 
-if ! command -v pnpm &> /dev/null; then
-  echo "The 'pnpm' tool is required. cd to the repo directory and type 'corepack enable'"
-  echo "https://github.com/lichess-org/lila/wiki/Lichess-Development-Onboarding"
-  exit 1
-fi
+corepack enable
 
 pnpm install --silent --ignore-workspace
 
