Move all tsc output to dist subdirectories
Requries node >v12.20.0 or >v14.13.0

diff --git a/ui/build b/ui/build
--- a/ui/build
+++ b/ui/build
@@ -8,7 +8,7 @@ nodever="$(node --version)"
 echo "node: $nodever"
 echo "yarn: $(yarn --version)"
 
-[[ "$nodever" =~ ^v1[2-6]\.[0-9]+\.[0-9]+$ ]] || { echo "Node version >=12 and <=16 required. Found: $nodever"; exit 1; }
+[[ "$nodever" =~ ^(v12\.[2-9][0-9]\.[0-9]+)|(v14\.1[3-9]\.[0-9]+)|(v1[5-6]\.[0-9]+\.[0-9]+)$ ]] || { echo "Node version >=12.20 or >=14.13 and <=16 required. Found: $nodever"; exit 1; }
 
 cd "$(git rev-parse --show-toplevel)"
 
